import { Referral } from "@modules/referrals/referral.model";
import { Injury } from "@modules/injuries/injury.model";
import { logger } from "@config/logger";

const SEVERITY_TO_PRIORITY: Record<string, string> = {
  Critical: "Critical",
  Severe: "High",
  Moderate: "Medium",
  Minor: "Low",
};

/**
 * Auto-generates a Medical case (referral) for every injury.
 * The case is the workflow wrapper; the injury is the medical detail.
 */
export async function generateAutoReferralForInjury(
  injuryId: string,
  playerId: string,
  createdBy: string,
): Promise<void> {
  const injury = await Injury.findByPk(injuryId);
  if (!injury) return;

  // Avoid duplicates — one case per injury
  const existing = await Referral.findOne({
    where: { injuryId } as any,
  });
  if (existing) return;

  const priority = SEVERITY_TO_PRIORITY[injury.severity] ?? "Medium";

  await Referral.create({
    referralType: "Medical",
    playerId,
    injuryId,
    triggerDesc: `${injury.injuryType} — ${injury.bodyPart}`,
    isAutoGenerated: true,
    status: "Open",
    priority,
    createdBy,
  } as any);

  logger.info("Auto-generated Medical case for injury", {
    injuryId,
    priority,
  });
}
