import { ExerciseLibrary, FoodItem } from "../modules/gym/gym.model";

export async function seedExerciseLibrary(): Promise<void> {
  const exercises = [
    // ── Chest ──
    {
      nameEn: "Barbell Bench Press",
      nameAr: "ضغط البنش بالبار",
      muscleGroup: "Chest",
      equipment: "Barbell",
      movementType: "Push",
      difficulty: "Intermediate",
    },
    {
      nameEn: "Incline Dumbbell Press",
      nameAr: "ضغط مائل بالدمبل",
      muscleGroup: "Chest",
      equipment: "Dumbbell",
      movementType: "Push",
      difficulty: "Intermediate",
    },
    {
      nameEn: "Decline Bench Press",
      nameAr: "ضغط منخفض بالبار",
      muscleGroup: "Chest",
      equipment: "Barbell",
      movementType: "Push",
      difficulty: "Intermediate",
    },
    {
      nameEn: "Dumbbell Flyes",
      nameAr: "فتح صدر بالدمبل",
      muscleGroup: "Chest",
      equipment: "Dumbbell",
      movementType: "Isolation",
      difficulty: "Beginner",
    },
    {
      nameEn: "Cable Crossover",
      nameAr: "كروس أوفر كيبل",
      muscleGroup: "Chest",
      equipment: "Cable",
      movementType: "Isolation",
      difficulty: "Intermediate",
    },
    {
      nameEn: "Push-Ups",
      nameAr: "تمرين الضغط",
      muscleGroup: "Chest",
      equipment: "Bodyweight",
      movementType: "Push",
      difficulty: "Beginner",
    },
    {
      nameEn: "Chest Dips",
      nameAr: "تمرين المتوازي للصدر",
      muscleGroup: "Chest",
      equipment: "Bodyweight",
      movementType: "Push",
      difficulty: "Intermediate",
    },
    {
      nameEn: "Machine Chest Press",
      nameAr: "ضغط صدر بالآلة",
      muscleGroup: "Chest",
      equipment: "Machine",
      movementType: "Push",
      difficulty: "Beginner",
    },

    // ── Back ──
    {
      nameEn: "Barbell Deadlift",
      nameAr: "رفعة ميتة بالبار",
      muscleGroup: "Back",
      equipment: "Barbell",
      movementType: "Pull",
      difficulty: "Advanced",
    },
    {
      nameEn: "Pull-Ups",
      nameAr: "تمرين العقلة",
      muscleGroup: "Back",
      equipment: "Bodyweight",
      movementType: "Pull",
      difficulty: "Intermediate",
    },
    {
      nameEn: "Barbell Row",
      nameAr: "تجديف بالبار",
      muscleGroup: "Back",
      equipment: "Barbell",
      movementType: "Pull",
      difficulty: "Intermediate",
    },
    {
      nameEn: "Lat Pulldown",
      nameAr: "سحب علوي",
      muscleGroup: "Back",
      equipment: "Cable",
      movementType: "Pull",
      difficulty: "Beginner",
    },
    {
      nameEn: "Seated Cable Row",
      nameAr: "تجديف كيبل جالس",
      muscleGroup: "Back",
      equipment: "Cable",
      movementType: "Pull",
      difficulty: "Beginner",
    },
    {
      nameEn: "T-Bar Row",
      nameAr: "تجديف تي بار",
      muscleGroup: "Back",
      equipment: "Barbell",
      movementType: "Pull",
      difficulty: "Intermediate",
    },
    {
      nameEn: "Single Arm Dumbbell Row",
      nameAr: "تجديف بذراع واحدة",
      muscleGroup: "Back",
      equipment: "Dumbbell",
      movementType: "Pull",
      difficulty: "Beginner",
    },
    {
      nameEn: "Face Pull",
      nameAr: "سحب للوجه",
      muscleGroup: "Back",
      secondaryMuscles: "Rear Delts",
      equipment: "Cable",
      movementType: "Pull",
      difficulty: "Beginner",
    },

    // ── Shoulders ──
    {
      nameEn: "Overhead Press",
      nameAr: "ضغط كتف بالبار",
      muscleGroup: "Shoulders",
      equipment: "Barbell",
      movementType: "Push",
      difficulty: "Intermediate",
    },
    {
      nameEn: "Dumbbell Lateral Raise",
      nameAr: "رفع جانبي بالدمبل",
      muscleGroup: "Shoulders",
      equipment: "Dumbbell",
      movementType: "Isolation",
      difficulty: "Beginner",
    },
    {
      nameEn: "Arnold Press",
      nameAr: "أرنولد بريس",
      muscleGroup: "Shoulders",
      equipment: "Dumbbell",
      movementType: "Push",
      difficulty: "Intermediate",
    },
    {
      nameEn: "Front Raise",
      nameAr: "رفع أمامي",
      muscleGroup: "Shoulders",
      equipment: "Dumbbell",
      movementType: "Isolation",
      difficulty: "Beginner",
    },
    {
      nameEn: "Reverse Pec Deck",
      nameAr: "فتح خلفي بالآلة",
      muscleGroup: "Shoulders",
      secondaryMuscles: "Rear Delts",
      equipment: "Machine",
      movementType: "Isolation",
      difficulty: "Beginner",
    },
    {
      nameEn: "Upright Row",
      nameAr: "تجديف عمودي",
      muscleGroup: "Shoulders",
      equipment: "Barbell",
      movementType: "Pull",
      difficulty: "Intermediate",
    },

    // ── Legs ──
    {
      nameEn: "Barbell Squat",
      nameAr: "قرفصاء بالبار",
      muscleGroup: "Legs",
      equipment: "Barbell",
      movementType: "Compound",
      difficulty: "Advanced",
    },
    {
      nameEn: "Leg Press",
      nameAr: "ضغط أرجل بالآلة",
      muscleGroup: "Legs",
      equipment: "Machine",
      movementType: "Compound",
      difficulty: "Beginner",
    },
    {
      nameEn: "Romanian Deadlift",
      nameAr: "رفعة رومانية",
      muscleGroup: "Legs",
      secondaryMuscles: "Hamstrings, Glutes",
      equipment: "Barbell",
      movementType: "Pull",
      difficulty: "Intermediate",
    },
    {
      nameEn: "Leg Extension",
      nameAr: "تمديد أرجل",
      muscleGroup: "Legs",
      equipment: "Machine",
      movementType: "Isolation",
      difficulty: "Beginner",
    },
    {
      nameEn: "Leg Curl",
      nameAr: "ثني أرجل",
      muscleGroup: "Legs",
      equipment: "Machine",
      movementType: "Isolation",
      difficulty: "Beginner",
    },
    {
      nameEn: "Bulgarian Split Squat",
      nameAr: "قرفصاء بلغارية",
      muscleGroup: "Legs",
      equipment: "Dumbbell",
      movementType: "Compound",
      difficulty: "Intermediate",
    },
    {
      nameEn: "Walking Lunges",
      nameAr: "طعنات مشي",
      muscleGroup: "Legs",
      equipment: "Dumbbell",
      movementType: "Compound",
      difficulty: "Beginner",
    },
    {
      nameEn: "Calf Raise",
      nameAr: "رفع ربلة الساق",
      muscleGroup: "Legs",
      equipment: "Machine",
      movementType: "Isolation",
      difficulty: "Beginner",
    },
    {
      nameEn: "Hip Thrust",
      nameAr: "ثراست الورك",
      muscleGroup: "Legs",
      secondaryMuscles: "Glutes",
      equipment: "Barbell",
      movementType: "Compound",
      difficulty: "Intermediate",
    },
    {
      nameEn: "Front Squat",
      nameAr: "قرفصاء أمامية",
      muscleGroup: "Legs",
      equipment: "Barbell",
      movementType: "Compound",
      difficulty: "Advanced",
    },

    // ── Arms ──
    {
      nameEn: "Barbell Curl",
      nameAr: "كيرل بالبار",
      muscleGroup: "Arms",
      secondaryMuscles: "Biceps",
      equipment: "Barbell",
      movementType: "Isolation",
      difficulty: "Beginner",
    },
    {
      nameEn: "Hammer Curl",
      nameAr: "هامر كيرل",
      muscleGroup: "Arms",
      secondaryMuscles: "Biceps",
      equipment: "Dumbbell",
      movementType: "Isolation",
      difficulty: "Beginner",
    },
    {
      nameEn: "Tricep Pushdown",
      nameAr: "ضغط تراي بالكيبل",
      muscleGroup: "Arms",
      secondaryMuscles: "Triceps",
      equipment: "Cable",
      movementType: "Isolation",
      difficulty: "Beginner",
    },
    {
      nameEn: "Skull Crushers",
      nameAr: "سكل كراشر",
      muscleGroup: "Arms",
      secondaryMuscles: "Triceps",
      equipment: "Barbell",
      movementType: "Isolation",
      difficulty: "Intermediate",
    },
    {
      nameEn: "Preacher Curl",
      nameAr: "كيرل بريتشر",
      muscleGroup: "Arms",
      secondaryMuscles: "Biceps",
      equipment: "Barbell",
      movementType: "Isolation",
      difficulty: "Beginner",
    },
    {
      nameEn: "Close-Grip Bench Press",
      nameAr: "ضغط ضيق",
      muscleGroup: "Arms",
      secondaryMuscles: "Triceps",
      equipment: "Barbell",
      movementType: "Push",
      difficulty: "Intermediate",
    },
    {
      nameEn: "Concentration Curl",
      nameAr: "كيرل تركيز",
      muscleGroup: "Arms",
      secondaryMuscles: "Biceps",
      equipment: "Dumbbell",
      movementType: "Isolation",
      difficulty: "Beginner",
    },

    // ── Core ──
    {
      nameEn: "Plank",
      nameAr: "تمرين البلانك",
      muscleGroup: "Core",
      equipment: "Bodyweight",
      movementType: "Isometric",
      difficulty: "Beginner",
    },
    {
      nameEn: "Hanging Leg Raise",
      nameAr: "رفع أرجل معلق",
      muscleGroup: "Core",
      equipment: "Bodyweight",
      movementType: "Isolation",
      difficulty: "Intermediate",
    },
    {
      nameEn: "Cable Crunch",
      nameAr: "كرانش بالكيبل",
      muscleGroup: "Core",
      equipment: "Cable",
      movementType: "Isolation",
      difficulty: "Beginner",
    },
    {
      nameEn: "Russian Twist",
      nameAr: "لف روسي",
      muscleGroup: "Core",
      equipment: "Bodyweight",
      movementType: "Rotation",
      difficulty: "Beginner",
    },
    {
      nameEn: "Ab Wheel Rollout",
      nameAr: "عجلة البطن",
      muscleGroup: "Core",
      equipment: "Ab Wheel",
      movementType: "Compound",
      difficulty: "Advanced",
    },
    {
      nameEn: "Bicycle Crunch",
      nameAr: "كرانش دراجة",
      muscleGroup: "Core",
      equipment: "Bodyweight",
      movementType: "Isolation",
      difficulty: "Beginner",
    },
    {
      nameEn: "Side Plank",
      nameAr: "بلانك جانبي",
      muscleGroup: "Core",
      equipment: "Bodyweight",
      movementType: "Isometric",
      difficulty: "Beginner",
    },

    // ── Football-Specific / Functional ──
    {
      nameEn: "Box Jump",
      nameAr: "قفز على الصندوق",
      muscleGroup: "Legs",
      equipment: "Box",
      movementType: "Plyometric",
      difficulty: "Intermediate",
    },
    {
      nameEn: "Medicine Ball Throw",
      nameAr: "رمي كرة طبية",
      muscleGroup: "Core",
      equipment: "Medicine Ball",
      movementType: "Explosive",
      difficulty: "Beginner",
    },
    {
      nameEn: "Battle Ropes",
      nameAr: "حبال المعركة",
      muscleGroup: "Full Body",
      equipment: "Battle Ropes",
      movementType: "Cardio",
      difficulty: "Intermediate",
    },
    {
      nameEn: "Sled Push",
      nameAr: "دفع الزلاجة",
      muscleGroup: "Full Body",
      equipment: "Sled",
      movementType: "Compound",
      difficulty: "Intermediate",
    },
    {
      nameEn: "Kettlebell Swing",
      nameAr: "سوينغ كيتل بيل",
      muscleGroup: "Full Body",
      secondaryMuscles: "Glutes, Hamstrings",
      equipment: "Kettlebell",
      movementType: "Explosive",
      difficulty: "Intermediate",
    },
    {
      nameEn: "Single Leg RDL",
      nameAr: "رفعة رومانية بساق واحدة",
      muscleGroup: "Legs",
      secondaryMuscles: "Balance",
      equipment: "Dumbbell",
      movementType: "Compound",
      difficulty: "Intermediate",
    },
    {
      nameEn: "Lateral Band Walk",
      nameAr: "مشي جانبي بالمقاومة",
      muscleGroup: "Legs",
      secondaryMuscles: "Hip Abductors",
      equipment: "Resistance Band",
      movementType: "Activation",
      difficulty: "Beginner",
    },
    {
      nameEn: "TRX Row",
      nameAr: "تجديف TRX",
      muscleGroup: "Back",
      equipment: "TRX",
      movementType: "Pull",
      difficulty: "Beginner",
    },
    {
      nameEn: "Agility Ladder Drills",
      nameAr: "تمارين سلم الرشاقة",
      muscleGroup: "Full Body",
      equipment: "Agility Ladder",
      movementType: "Cardio",
      difficulty: "Beginner",
    },
    {
      nameEn: "Nordic Hamstring Curl",
      nameAr: "نورديك كيرل",
      muscleGroup: "Legs",
      secondaryMuscles: "Hamstrings",
      equipment: "Bodyweight",
      movementType: "Isolation",
      difficulty: "Advanced",
    },
  ];

  await ExerciseLibrary.bulkCreate(exercises as any, {
    updateOnDuplicate: [
      "name_ar",
      "muscle_group",
      "equipment",
      "movement_type",
      "difficulty",
    ],
  });
  console.log(`  ✅ Seeded ${exercises.length} exercises`);
}

export async function seedFoodDatabase(): Promise<void> {
  const foods = [
    // ── Proteins ──
    {
      nameEn: "Chicken Breast (grilled)",
      nameAr: "صدر دجاج مشوي",
      category: "Protein",
      caloriesPer100g: 165,
      proteinPer100g: 31,
      carbsPer100g: 0,
      fatPer100g: 3.6,
    },
    {
      nameEn: "Beef Steak (lean)",
      nameAr: "ستيك لحم بقر",
      category: "Protein",
      caloriesPer100g: 271,
      proteinPer100g: 26,
      carbsPer100g: 0,
      fatPer100g: 18,
    },
    {
      nameEn: "Salmon Fillet",
      nameAr: "فيليه سلمون",
      category: "Protein",
      caloriesPer100g: 208,
      proteinPer100g: 20,
      carbsPer100g: 0,
      fatPer100g: 13,
    },
    {
      nameEn: "Eggs (whole)",
      nameAr: "بيض كامل",
      category: "Protein",
      caloriesPer100g: 155,
      proteinPer100g: 13,
      carbsPer100g: 1.1,
      fatPer100g: 11,
    },
    {
      nameEn: "Egg Whites",
      nameAr: "بياض البيض",
      category: "Protein",
      caloriesPer100g: 52,
      proteinPer100g: 11,
      carbsPer100g: 0.7,
      fatPer100g: 0.2,
    },
    {
      nameEn: "Tuna (canned)",
      nameAr: "تونة معلبة",
      category: "Protein",
      caloriesPer100g: 132,
      proteinPer100g: 29,
      carbsPer100g: 0,
      fatPer100g: 1,
    },
    {
      nameEn: "Shrimp",
      nameAr: "ربيان",
      category: "Protein",
      caloriesPer100g: 99,
      proteinPer100g: 24,
      carbsPer100g: 0.2,
      fatPer100g: 0.3,
    },
    {
      nameEn: "Greek Yogurt",
      nameAr: "زبادي يوناني",
      category: "Protein",
      caloriesPer100g: 59,
      proteinPer100g: 10,
      carbsPer100g: 3.6,
      fatPer100g: 0.4,
    },
    {
      nameEn: "Whey Protein (scoop)",
      nameAr: "واي بروتين (سكوب)",
      category: "Protein",
      caloriesPer100g: 400,
      proteinPer100g: 80,
      carbsPer100g: 8,
      fatPer100g: 4,
      servingSize: 30,
      servingUnit: "g",
    },
    {
      nameEn: "Lamb (lean)",
      nameAr: "لحم غنم",
      category: "Protein",
      caloriesPer100g: 282,
      proteinPer100g: 25,
      carbsPer100g: 0,
      fatPer100g: 20,
    },

    // ── Carbohydrates ──
    {
      nameEn: "White Rice (cooked)",
      nameAr: "أرز أبيض مطبوخ",
      category: "Carbs",
      caloriesPer100g: 130,
      proteinPer100g: 2.7,
      carbsPer100g: 28,
      fatPer100g: 0.3,
    },
    {
      nameEn: "Brown Rice (cooked)",
      nameAr: "أرز بني مطبوخ",
      category: "Carbs",
      caloriesPer100g: 112,
      proteinPer100g: 2.6,
      carbsPer100g: 24,
      fatPer100g: 0.9,
    },
    {
      nameEn: "Oats",
      nameAr: "شوفان",
      category: "Carbs",
      caloriesPer100g: 389,
      proteinPer100g: 17,
      carbsPer100g: 66,
      fatPer100g: 7,
    },
    {
      nameEn: "Sweet Potato",
      nameAr: "بطاطا حلوة",
      category: "Carbs",
      caloriesPer100g: 86,
      proteinPer100g: 1.6,
      carbsPer100g: 20,
      fatPer100g: 0.1,
    },
    {
      nameEn: "White Bread",
      nameAr: "خبز أبيض",
      category: "Carbs",
      caloriesPer100g: 265,
      proteinPer100g: 9,
      carbsPer100g: 49,
      fatPer100g: 3.2,
    },
    {
      nameEn: "Arabic Bread (Pita)",
      nameAr: "خبز عربي",
      category: "Carbs",
      caloriesPer100g: 275,
      proteinPer100g: 9.1,
      carbsPer100g: 55,
      fatPer100g: 1.2,
    },
    {
      nameEn: "Pasta (cooked)",
      nameAr: "معكرونة مطبوخة",
      category: "Carbs",
      caloriesPer100g: 131,
      proteinPer100g: 5,
      carbsPer100g: 25,
      fatPer100g: 1.1,
    },
    {
      nameEn: "Potato (boiled)",
      nameAr: "بطاطس مسلوقة",
      category: "Carbs",
      caloriesPer100g: 77,
      proteinPer100g: 2,
      carbsPer100g: 17,
      fatPer100g: 0.1,
    },
    {
      nameEn: "Banana",
      nameAr: "موز",
      category: "Carbs",
      caloriesPer100g: 89,
      proteinPer100g: 1.1,
      carbsPer100g: 23,
      fatPer100g: 0.3,
    },
    {
      nameEn: "Dates (Medjool)",
      nameAr: "تمر مدجول",
      category: "Carbs",
      caloriesPer100g: 277,
      proteinPer100g: 1.8,
      carbsPer100g: 75,
      fatPer100g: 0.2,
    },

    // ── Fats ──
    {
      nameEn: "Olive Oil",
      nameAr: "زيت زيتون",
      category: "Fats",
      caloriesPer100g: 884,
      proteinPer100g: 0,
      carbsPer100g: 0,
      fatPer100g: 100,
    },
    {
      nameEn: "Avocado",
      nameAr: "أفوكادو",
      category: "Fats",
      caloriesPer100g: 160,
      proteinPer100g: 2,
      carbsPer100g: 9,
      fatPer100g: 15,
    },
    {
      nameEn: "Almonds",
      nameAr: "لوز",
      category: "Fats",
      caloriesPer100g: 579,
      proteinPer100g: 21,
      carbsPer100g: 22,
      fatPer100g: 50,
    },
    {
      nameEn: "Peanut Butter",
      nameAr: "زبدة فول سوداني",
      category: "Fats",
      caloriesPer100g: 588,
      proteinPer100g: 25,
      carbsPer100g: 20,
      fatPer100g: 50,
    },
    {
      nameEn: "Walnuts",
      nameAr: "جوز",
      category: "Fats",
      caloriesPer100g: 654,
      proteinPer100g: 15,
      carbsPer100g: 14,
      fatPer100g: 65,
    },
    {
      nameEn: "Coconut Oil",
      nameAr: "زيت جوز الهند",
      category: "Fats",
      caloriesPer100g: 862,
      proteinPer100g: 0,
      carbsPer100g: 0,
      fatPer100g: 100,
    },

    // ── Saudi/MENA Traditional Foods ──
    {
      nameEn: "Kabsa (chicken)",
      nameAr: "كبسة دجاج",
      category: "Traditional",
      caloriesPer100g: 180,
      proteinPer100g: 12,
      carbsPer100g: 20,
      fatPer100g: 6,
    },
    {
      nameEn: "Jareesh",
      nameAr: "جريش",
      category: "Traditional",
      caloriesPer100g: 120,
      proteinPer100g: 4,
      carbsPer100g: 22,
      fatPer100g: 2,
    },
    {
      nameEn: "Harees",
      nameAr: "هريس",
      category: "Traditional",
      caloriesPer100g: 150,
      proteinPer100g: 8,
      carbsPer100g: 20,
      fatPer100g: 4,
    },
    {
      nameEn: "Mathbi (lamb)",
      nameAr: "مضبي لحم",
      category: "Traditional",
      caloriesPer100g: 250,
      proteinPer100g: 18,
      carbsPer100g: 15,
      fatPer100g: 14,
    },
    {
      nameEn: "Mandi (chicken)",
      nameAr: "مندي دجاج",
      category: "Traditional",
      caloriesPer100g: 190,
      proteinPer100g: 14,
      carbsPer100g: 22,
      fatPer100g: 5,
    },
    {
      nameEn: "Saleeg",
      nameAr: "سليق",
      category: "Traditional",
      caloriesPer100g: 160,
      proteinPer100g: 10,
      carbsPer100g: 18,
      fatPer100g: 6,
    },
    {
      nameEn: "Mutabbaq",
      nameAr: "مطبق",
      category: "Traditional",
      caloriesPer100g: 300,
      proteinPer100g: 8,
      carbsPer100g: 30,
      fatPer100g: 16,
    },
    {
      nameEn: "Foul Medames",
      nameAr: "فول مدمس",
      category: "Traditional",
      caloriesPer100g: 110,
      proteinPer100g: 8,
      carbsPer100g: 15,
      fatPer100g: 2,
    },
    {
      nameEn: "Hummus",
      nameAr: "حمص",
      category: "Traditional",
      caloriesPer100g: 166,
      proteinPer100g: 8,
      carbsPer100g: 14,
      fatPer100g: 10,
    },
    {
      nameEn: "Labneh",
      nameAr: "لبنة",
      category: "Traditional",
      caloriesPer100g: 160,
      proteinPer100g: 8,
      carbsPer100g: 4,
      fatPer100g: 12,
    },
    {
      nameEn: "Arabic Coffee",
      nameAr: "قهوة عربية",
      category: "Beverages",
      caloriesPer100g: 2,
      proteinPer100g: 0.1,
      carbsPer100g: 0,
      fatPer100g: 0,
    },
    {
      nameEn: "Laban (buttermilk)",
      nameAr: "لبن",
      category: "Beverages",
      caloriesPer100g: 40,
      proteinPer100g: 3.3,
      carbsPer100g: 5,
      fatPer100g: 1,
    },
    {
      nameEn: "Shawarma (chicken)",
      nameAr: "شاورما دجاج",
      category: "Traditional",
      caloriesPer100g: 175,
      proteinPer100g: 16,
      carbsPer100g: 10,
      fatPer100g: 8,
    },
    {
      nameEn: "Fattoush Salad",
      nameAr: "سلطة فتوش",
      category: "Traditional",
      caloriesPer100g: 55,
      proteinPer100g: 1.5,
      carbsPer100g: 7,
      fatPer100g: 3,
    },
    {
      nameEn: "Tabbouleh",
      nameAr: "تبولة",
      category: "Traditional",
      caloriesPer100g: 65,
      proteinPer100g: 2,
      carbsPer100g: 8,
      fatPer100g: 3,
    },

    // ── Vegetables ──
    {
      nameEn: "Broccoli",
      nameAr: "بروكلي",
      category: "Vegetables",
      caloriesPer100g: 34,
      proteinPer100g: 2.8,
      carbsPer100g: 7,
      fatPer100g: 0.4,
    },
    {
      nameEn: "Spinach",
      nameAr: "سبانخ",
      category: "Vegetables",
      caloriesPer100g: 23,
      proteinPer100g: 2.9,
      carbsPer100g: 3.6,
      fatPer100g: 0.4,
    },
    {
      nameEn: "Cucumber",
      nameAr: "خيار",
      category: "Vegetables",
      caloriesPer100g: 15,
      proteinPer100g: 0.7,
      carbsPer100g: 3.6,
      fatPer100g: 0.1,
    },
    {
      nameEn: "Tomato",
      nameAr: "طماطم",
      category: "Vegetables",
      caloriesPer100g: 18,
      proteinPer100g: 0.9,
      carbsPer100g: 3.9,
      fatPer100g: 0.2,
    },

    // ── Fruits ──
    {
      nameEn: "Apple",
      nameAr: "تفاح",
      category: "Fruits",
      caloriesPer100g: 52,
      proteinPer100g: 0.3,
      carbsPer100g: 14,
      fatPer100g: 0.2,
    },
    {
      nameEn: "Orange",
      nameAr: "برتقال",
      category: "Fruits",
      caloriesPer100g: 47,
      proteinPer100g: 0.9,
      carbsPer100g: 12,
      fatPer100g: 0.1,
    },
    {
      nameEn: "Watermelon",
      nameAr: "بطيخ",
      category: "Fruits",
      caloriesPer100g: 30,
      proteinPer100g: 0.6,
      carbsPer100g: 8,
      fatPer100g: 0.2,
    },
    {
      nameEn: "Mango",
      nameAr: "مانجو",
      category: "Fruits",
      caloriesPer100g: 60,
      proteinPer100g: 0.8,
      carbsPer100g: 15,
      fatPer100g: 0.4,
    },

    // ── Dairy ──
    {
      nameEn: "Whole Milk",
      nameAr: "حليب كامل",
      category: "Dairy",
      caloriesPer100g: 61,
      proteinPer100g: 3.2,
      carbsPer100g: 4.8,
      fatPer100g: 3.3,
    },
    {
      nameEn: "Low-Fat Milk",
      nameAr: "حليب قليل الدسم",
      category: "Dairy",
      caloriesPer100g: 42,
      proteinPer100g: 3.4,
      carbsPer100g: 5,
      fatPer100g: 1,
    },
    {
      nameEn: "Cheese (white)",
      nameAr: "جبنة بيضاء",
      category: "Dairy",
      caloriesPer100g: 264,
      proteinPer100g: 18,
      carbsPer100g: 2,
      fatPer100g: 21,
    },

    // ── Snacks / Supplements ──
    {
      nameEn: "Protein Bar",
      nameAr: "بار بروتين",
      category: "Supplements",
      caloriesPer100g: 370,
      proteinPer100g: 30,
      carbsPer100g: 35,
      fatPer100g: 12,
      servingSize: 60,
      servingUnit: "g",
    },
    {
      nameEn: "Honey",
      nameAr: "عسل",
      category: "Sweeteners",
      caloriesPer100g: 304,
      proteinPer100g: 0.3,
      carbsPer100g: 82,
      fatPer100g: 0,
    },
    {
      nameEn: "Rice Cakes",
      nameAr: "كعك الأرز",
      category: "Snacks",
      caloriesPer100g: 387,
      proteinPer100g: 8,
      carbsPer100g: 81,
      fatPer100g: 3,
    },
  ];

  await FoodItem.bulkCreate(foods as any, {
    updateOnDuplicate: [
      "name_ar",
      "category",
      "calories_per_100g",
      "protein_per_100g",
      "carbs_per_100g",
      "fat_per_100g",
    ],
  });
  console.log(`  ✅ Seeded ${foods.length} food items`);
}

export async function seedGymData(): Promise<void> {
  await seedExerciseLibrary();
  await seedFoodDatabase();
}
