import { DataTypes, Model, Optional } from "sequelize";
import { sequelize } from "@config/database";

// ── Enum Types ──

export type ReferralType =
  | "Performance" // legacy
  | "Physical"
  | "Skill"
  | "Tactical"
  | "Mental"
  | "Nutrition"
  | "Medical"
  | "Administrative"
  | "SportDecision"
  | "Goalkeeper";

export type ReferralStatus = "Open" | "InProgress" | "Waiting" | "Closed";
export type ReferralPriority = "Low" | "Medium" | "High" | "Critical";

export type ReferralTarget =
  | "FitnessCoach"
  | "Coach"
  | "SkillCoach"
  | "TacticalCoach"
  | "GoalkeeperCoach"
  | "Analyst"
  | "NutritionSpecialist"
  | "MentalCoach"
  | "Manager";

export type ReceivingParty =
  | "AgencyManagement"
  | "MentalSpecialist"
  | "PhysicalSpecialist"
  | "ExternalCoach"
  | "Legal"
  | "Finance"
  | "PerformanceAnalyst";

// ── Attribute Interfaces ──

export interface ReferralAttributes {
  id: string;
  referralType: ReferralType;
  playerId: string;
  injuryId?: string | null;
  referralTarget?: ReferralTarget | null;
  triggerDesc?: string | null;
  triggerRuleId?: string | null;
  isAutoGenerated: boolean;
  status: ReferralStatus;
  priority: ReferralPriority;
  assignedTo?: string | null;
  assignedAt?: Date | null;
  dueDate?: string | null;
  closedAt?: Date | null;
  closureNotes?: string | null;
  evidenceCount: number;
  /**
   * Computed at query time via a correlated subquery — never stored.
   * Always present on read paths that opt-in via `referralAttributesWithComputed`
   * (see referral.service.ts).
   */
  sessionCount?: number;
  outcome?: string | null;
  notes?: string | null;
  isRestricted: boolean;
  resultingTicketId?: string | null;
  restrictedTo?: string[] | null;
  receivingParty?: ReceivingParty | null;
  externalRef?: string | null;
  createdBy?: string | null;
  displayId?: string | null;
  createdAt?: Date;
  updatedAt?: Date;
}

interface ReferralCreationAttributes extends Optional<
  ReferralAttributes,
  | "id"
  | "isAutoGenerated"
  | "status"
  | "priority"
  | "evidenceCount"
  | "sessionCount"
  | "resultingTicketId"
  | "isRestricted"
  | "referralTarget"
  | "receivingParty"
  | "externalRef"
  | "closureNotes"
  | "closedAt"
  | "displayId"
  | "createdAt"
  | "updatedAt"
> {}

// ── Model Class ──

export class Referral
  extends Model<ReferralAttributes, ReferralCreationAttributes>
  implements ReferralAttributes
{
  declare id: string;
  declare referralType: ReferralType;
  declare playerId: string;
  declare injuryId: string | null;
  declare referralTarget: ReferralTarget | null;
  declare triggerDesc: string | null;
  declare triggerRuleId: string | null;
  declare isAutoGenerated: boolean;
  declare status: ReferralStatus;
  declare priority: ReferralPriority;
  declare assignedTo: string | null;
  declare assignedAt: Date | null;
  declare dueDate: string | null;
  declare closedAt: Date | null;
  declare closureNotes: string | null;
  declare evidenceCount: number;
  declare sessionCount: number | undefined;
  declare outcome: string | null;
  declare notes: string | null;
  declare isRestricted: boolean;
  declare resultingTicketId: string | null;
  declare restrictedTo: string[] | null;
  declare receivingParty: ReceivingParty | null;
  declare externalRef: string | null;
  declare createdBy: string | null;
  declare displayId: string | null;
  declare createdAt: Date;
  declare updatedAt: Date;
}

// ── Initialization ──

Referral.init(
  {
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
    },
    referralType: {
      type: DataTypes.STRING(50),
      allowNull: false,
      field: "referral_type",
    },
    playerId: {
      type: DataTypes.UUID,
      allowNull: false,
      field: "player_id",
    },
    injuryId: {
      type: DataTypes.UUID,
      allowNull: true,
      field: "injury_id",
      references: { model: "injuries", key: "id" },
    },
    referralTarget: {
      type: DataTypes.STRING(50),
      field: "referral_target",
    },
    triggerDesc: {
      type: DataTypes.TEXT,
      field: "trigger_desc",
    },
    triggerRuleId: {
      type: DataTypes.UUID,
      field: "trigger_rule_id",
    },
    isAutoGenerated: {
      type: DataTypes.BOOLEAN,
      defaultValue: false,
      field: "is_auto_generated",
    },
    status: {
      type: DataTypes.STRING(50),
      defaultValue: "Open",
    },
    priority: {
      type: DataTypes.STRING(50),
      defaultValue: "Medium",
    },
    assignedTo: {
      type: DataTypes.UUID,
      field: "assigned_to",
    },
    assignedAt: {
      type: DataTypes.DATE,
      field: "assigned_at",
    },
    dueDate: {
      type: DataTypes.DATEONLY,
      field: "due_date",
    },
    closedAt: {
      type: DataTypes.DATE,
      field: "closed_at",
    },
    closureNotes: {
      type: DataTypes.TEXT,
      field: "closure_notes",
    },
    evidenceCount: {
      type: DataTypes.INTEGER,
      defaultValue: 0,
      field: "evidence_count",
    },
    outcome: {
      type: DataTypes.TEXT,
    },
    notes: {
      type: DataTypes.TEXT,
    },
    resultingTicketId: {
      type: DataTypes.UUID,
      field: "resulting_ticket_id",
      references: { model: "tickets", key: "id" },
    },
    isRestricted: {
      type: DataTypes.BOOLEAN,
      defaultValue: false,
      field: "is_restricted",
    },
    restrictedTo: {
      type: DataTypes.ARRAY(DataTypes.UUID),
      defaultValue: [],
      field: "restricted_to",
    },
    displayId: {
      type: DataTypes.STRING(20),
      unique: true,
    },
    createdBy: {
      type: DataTypes.UUID,
      field: "created_by",
    },
    receivingParty: {
      type: DataTypes.STRING(50),
      allowNull: true,
      field: "receiving_party",
    },
    externalRef: {
      type: DataTypes.STRING(255),
      allowNull: true,
      field: "external_ref",
    },
  },
  {
    sequelize,
    tableName: "referrals",
    underscored: true,
    timestamps: true,
  },
);
