import { DataTypes, Model, Optional } from 'sequelize';
import { sequelize } from '../../config/database';

// ── Enum Types ──

export type ReferralType = 'Performance' | 'Mental' | 'Medical';
export type ReferralStatus = 'Open' | 'InProgress' | 'Resolved' | 'Escalated';
export type ReferralPriority = 'Low' | 'Medium' | 'High' | 'Critical';

// ── Attribute Interfaces ──

export interface ReferralAttributes {
  id: string;
  referralType: ReferralType;
  playerId: string;
  triggerDesc?: string | null;
  triggerRuleId?: string | null;
  isAutoGenerated: boolean;
  status: ReferralStatus;
  priority: ReferralPriority;
  assignedTo?: string | null;
  assignedAt?: Date | null;
  dueDate?: string | null;
  resolvedAt?: Date | null;
  evidenceCount: number;
  sessionCount: number;
  outcome?: string | null;
  notes?: string | null;
  isRestricted: boolean;
  restrictedTo?: string[] | null;
  createdBy?: string | null;
  createdAt?: Date;
  updatedAt?: Date;
}

interface ReferralCreationAttributes extends Optional<
  ReferralAttributes,
  'id' | 'isAutoGenerated' | 'status' | 'priority' | 'evidenceCount' | 'sessionCount' | 'isRestricted' | 'createdAt' | 'updatedAt'
> {}

// ── Model Class ──

export class Referral extends Model<ReferralAttributes, ReferralCreationAttributes> implements ReferralAttributes {
  declare id: string;
  declare referralType: ReferralType;
  declare playerId: string;
  declare triggerDesc: string | null;
  declare triggerRuleId: string | null;
  declare isAutoGenerated: boolean;
  declare status: ReferralStatus;
  declare priority: ReferralPriority;
  declare assignedTo: string | null;
  declare assignedAt: Date | null;
  declare dueDate: string | null;
  declare resolvedAt: Date | null;
  declare evidenceCount: number;
  declare sessionCount: number;
  declare outcome: string | null;
  declare notes: string | null;
  declare isRestricted: boolean;
  declare restrictedTo: string[] | null;
  declare createdBy: string | null;
  declare createdAt: Date;
  declare updatedAt: Date;
}

// ── Initialization ──

Referral.init({
  id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    primaryKey: true,
  },
  referralType: {
    type: DataTypes.ENUM('Performance', 'Mental', 'Medical'),
    allowNull: false,
    field: 'referral_type',
  },
  playerId: {
    type: DataTypes.UUID,
    allowNull: false,
    field: 'player_id',
  },
  triggerDesc: {
    type: DataTypes.TEXT,
    field: 'trigger_desc',
  },
  triggerRuleId: {
    type: DataTypes.UUID,
    field: 'trigger_rule_id',
  },
  isAutoGenerated: {
    type: DataTypes.BOOLEAN,
    defaultValue: false,
    field: 'is_auto_generated',
  },
  status: {
    type: DataTypes.ENUM('Open', 'InProgress', 'Resolved', 'Escalated'),
    defaultValue: 'Open',
  },
  priority: {
    type: DataTypes.ENUM('Low', 'Medium', 'High', 'Critical'),
    defaultValue: 'Medium',
  },
  assignedTo: {
    type: DataTypes.UUID,
    field: 'assigned_to',
  },
  assignedAt: {
    type: DataTypes.DATE,
    field: 'assigned_at',
  },
  dueDate: {
    type: DataTypes.DATEONLY,
    field: 'due_date',
  },
  resolvedAt: {
    type: DataTypes.DATE,
    field: 'resolved_at',
  },
  evidenceCount: {
    type: DataTypes.INTEGER,
    defaultValue: 0,
    field: 'evidence_count',
  },
  sessionCount: {
    type: DataTypes.INTEGER,
    defaultValue: 0,
    field: 'session_count',
  },
  outcome: {
    type: DataTypes.TEXT,
  },
  notes: {
    type: DataTypes.TEXT,
  },
  isRestricted: {
    type: DataTypes.BOOLEAN,
    defaultValue: false,
    field: 'is_restricted',
  },
  restrictedTo: {
    type: DataTypes.ARRAY(DataTypes.UUID),
    defaultValue: [],
    field: 'restricted_to',
  },
  createdBy: {
    type: DataTypes.UUID,
    field: 'created_by',
  },
}, {
  sequelize,
  tableName: 'referrals',
  underscored: true,
  timestamps: true,
});